package com.pcsell.entity;
// Generated 16/01/2020 08:44:30 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Computadora generated by hbm2java
 */
public class Computadora  implements java.io.Serializable {


     private long id;
     private DiscoDuro discoDuroByDiscoDuro;
     private DiscoDuro discoDuroByDiscoDuroAdicional;
     private DisipadorCalor disipadorCalor;
     private FuentePoder fuentePoder;
     private Gabinete gabinete;
     private MemoriaRam memoriaRamByMemoriaRamAdicional;
     private MemoriaRam memoriaRamByMemoriaRam;
     private Procesador procesador;
     private TarjetaMadre tarjetaMadre;
     private TarjetaVideo tarjetaVideo;
     private BigDecimal costoTotal;
     private Set ventas = new HashSet(0);

    public Computadora() {
    }

	
    public Computadora(long id, DiscoDuro discoDuroByDiscoDuro, DiscoDuro discoDuroByDiscoDuroAdicional, DisipadorCalor disipadorCalor, FuentePoder fuentePoder, Gabinete gabinete, MemoriaRam memoriaRamByMemoriaRamAdicional, MemoriaRam memoriaRamByMemoriaRam, Procesador procesador, TarjetaMadre tarjetaMadre, TarjetaVideo tarjetaVideo, BigDecimal costoTotal) {
        this.id = id;
        this.discoDuroByDiscoDuro = discoDuroByDiscoDuro;
        this.discoDuroByDiscoDuroAdicional = discoDuroByDiscoDuroAdicional;
        this.disipadorCalor = disipadorCalor;
        this.fuentePoder = fuentePoder;
        this.gabinete = gabinete;
        this.memoriaRamByMemoriaRamAdicional = memoriaRamByMemoriaRamAdicional;
        this.memoriaRamByMemoriaRam = memoriaRamByMemoriaRam;
        this.procesador = procesador;
        this.tarjetaMadre = tarjetaMadre;
        this.tarjetaVideo = tarjetaVideo;
        this.costoTotal = costoTotal;
    }
    public Computadora(long id, DiscoDuro discoDuroByDiscoDuro, DiscoDuro discoDuroByDiscoDuroAdicional, DisipadorCalor disipadorCalor, FuentePoder fuentePoder, Gabinete gabinete, MemoriaRam memoriaRamByMemoriaRamAdicional, MemoriaRam memoriaRamByMemoriaRam, Procesador procesador, TarjetaMadre tarjetaMadre, TarjetaVideo tarjetaVideo, BigDecimal costoTotal, Set ventas) {
       this.id = id;
       this.discoDuroByDiscoDuro = discoDuroByDiscoDuro;
       this.discoDuroByDiscoDuroAdicional = discoDuroByDiscoDuroAdicional;
       this.disipadorCalor = disipadorCalor;
       this.fuentePoder = fuentePoder;
       this.gabinete = gabinete;
       this.memoriaRamByMemoriaRamAdicional = memoriaRamByMemoriaRamAdicional;
       this.memoriaRamByMemoriaRam = memoriaRamByMemoriaRam;
       this.procesador = procesador;
       this.tarjetaMadre = tarjetaMadre;
       this.tarjetaVideo = tarjetaVideo;
       this.costoTotal = costoTotal;
       this.ventas = ventas;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public DiscoDuro getDiscoDuroByDiscoDuro() {
        return this.discoDuroByDiscoDuro;
    }
    
    public void setDiscoDuroByDiscoDuro(DiscoDuro discoDuroByDiscoDuro) {
        this.discoDuroByDiscoDuro = discoDuroByDiscoDuro;
    }
    public DiscoDuro getDiscoDuroByDiscoDuroAdicional() {
        return this.discoDuroByDiscoDuroAdicional;
    }
    
    public void setDiscoDuroByDiscoDuroAdicional(DiscoDuro discoDuroByDiscoDuroAdicional) {
        this.discoDuroByDiscoDuroAdicional = discoDuroByDiscoDuroAdicional;
    }
    public DisipadorCalor getDisipadorCalor() {
        return this.disipadorCalor;
    }
    
    public void setDisipadorCalor(DisipadorCalor disipadorCalor) {
        this.disipadorCalor = disipadorCalor;
    }
    public FuentePoder getFuentePoder() {
        return this.fuentePoder;
    }
    
    public void setFuentePoder(FuentePoder fuentePoder) {
        this.fuentePoder = fuentePoder;
    }
    public Gabinete getGabinete() {
        return this.gabinete;
    }
    
    public void setGabinete(Gabinete gabinete) {
        this.gabinete = gabinete;
    }
    public MemoriaRam getMemoriaRamByMemoriaRamAdicional() {
        return this.memoriaRamByMemoriaRamAdicional;
    }
    
    public void setMemoriaRamByMemoriaRamAdicional(MemoriaRam memoriaRamByMemoriaRamAdicional) {
        this.memoriaRamByMemoriaRamAdicional = memoriaRamByMemoriaRamAdicional;
    }
    public MemoriaRam getMemoriaRamByMemoriaRam() {
        return this.memoriaRamByMemoriaRam;
    }
    
    public void setMemoriaRamByMemoriaRam(MemoriaRam memoriaRamByMemoriaRam) {
        this.memoriaRamByMemoriaRam = memoriaRamByMemoriaRam;
    }
    public Procesador getProcesador() {
        return this.procesador;
    }
    
    public void setProcesador(Procesador procesador) {
        this.procesador = procesador;
    }
    public TarjetaMadre getTarjetaMadre() {
        return this.tarjetaMadre;
    }
    
    public void setTarjetaMadre(TarjetaMadre tarjetaMadre) {
        this.tarjetaMadre = tarjetaMadre;
    }
    public TarjetaVideo getTarjetaVideo() {
        return this.tarjetaVideo;
    }
    
    public void setTarjetaVideo(TarjetaVideo tarjetaVideo) {
        this.tarjetaVideo = tarjetaVideo;
    }
    public BigDecimal getCostoTotal() {
        return this.costoTotal;
    }
    
    public void setCostoTotal(BigDecimal costoTotal) {
        this.costoTotal = costoTotal;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


