package com.pcsell.entity;
// Generated 17/01/2020 02:39:01 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Computadora generated by hbm2java
 */
public class Computadora  implements java.io.Serializable {


     private long id;
     private Discoduro discoduroByIddiscoduro;
     private Discoduro discoduroByIddiscoduroadicional;
     private Disipadorcalor disipadorcalor;
     private Fuentepoder fuentepoder;
     private Gabinete gabinete;
     private Memoriaram memoriaramByIdmemoriaramadicional;
     private Memoriaram memoriaramByIdmemoriaram;
     private Procesador procesador;
     private Tarjetamadre tarjetamadre;
     private Tarjetavideo tarjetavideo;
     private BigDecimal costototal;
     private Set ventas = new HashSet(0);

    public Computadora() {
    }

	
    public Computadora(long id, Discoduro discoduroByIddiscoduro, Discoduro discoduroByIddiscoduroadicional, Disipadorcalor disipadorcalor, Fuentepoder fuentepoder, Gabinete gabinete, Memoriaram memoriaramByIdmemoriaramadicional, Memoriaram memoriaramByIdmemoriaram, Procesador procesador, Tarjetamadre tarjetamadre, Tarjetavideo tarjetavideo, BigDecimal costototal) {
        this.id = id;
        this.discoduroByIddiscoduro = discoduroByIddiscoduro;
        this.discoduroByIddiscoduroadicional = discoduroByIddiscoduroadicional;
        this.disipadorcalor = disipadorcalor;
        this.fuentepoder = fuentepoder;
        this.gabinete = gabinete;
        this.memoriaramByIdmemoriaramadicional = memoriaramByIdmemoriaramadicional;
        this.memoriaramByIdmemoriaram = memoriaramByIdmemoriaram;
        this.procesador = procesador;
        this.tarjetamadre = tarjetamadre;
        this.tarjetavideo = tarjetavideo;
        this.costototal = costototal;
    }
    public Computadora(long id, Discoduro discoduroByIddiscoduro, Discoduro discoduroByIddiscoduroadicional, Disipadorcalor disipadorcalor, Fuentepoder fuentepoder, Gabinete gabinete, Memoriaram memoriaramByIdmemoriaramadicional, Memoriaram memoriaramByIdmemoriaram, Procesador procesador, Tarjetamadre tarjetamadre, Tarjetavideo tarjetavideo, BigDecimal costototal, Set ventas) {
       this.id = id;
       this.discoduroByIddiscoduro = discoduroByIddiscoduro;
       this.discoduroByIddiscoduroadicional = discoduroByIddiscoduroadicional;
       this.disipadorcalor = disipadorcalor;
       this.fuentepoder = fuentepoder;
       this.gabinete = gabinete;
       this.memoriaramByIdmemoriaramadicional = memoriaramByIdmemoriaramadicional;
       this.memoriaramByIdmemoriaram = memoriaramByIdmemoriaram;
       this.procesador = procesador;
       this.tarjetamadre = tarjetamadre;
       this.tarjetavideo = tarjetavideo;
       this.costototal = costototal;
       this.ventas = ventas;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Discoduro getDiscoduroByIddiscoduro() {
        return this.discoduroByIddiscoduro;
    }
    
    public void setDiscoduroByIddiscoduro(Discoduro discoduroByIddiscoduro) {
        this.discoduroByIddiscoduro = discoduroByIddiscoduro;
    }
    public Discoduro getDiscoduroByIddiscoduroadicional() {
        return this.discoduroByIddiscoduroadicional;
    }
    
    public void setDiscoduroByIddiscoduroadicional(Discoduro discoduroByIddiscoduroadicional) {
        this.discoduroByIddiscoduroadicional = discoduroByIddiscoduroadicional;
    }
    public Disipadorcalor getDisipadorcalor() {
        return this.disipadorcalor;
    }
    
    public void setDisipadorcalor(Disipadorcalor disipadorcalor) {
        this.disipadorcalor = disipadorcalor;
    }
    public Fuentepoder getFuentepoder() {
        return this.fuentepoder;
    }
    
    public void setFuentepoder(Fuentepoder fuentepoder) {
        this.fuentepoder = fuentepoder;
    }
    public Gabinete getGabinete() {
        return this.gabinete;
    }
    
    public void setGabinete(Gabinete gabinete) {
        this.gabinete = gabinete;
    }
    public Memoriaram getMemoriaramByIdmemoriaramadicional() {
        return this.memoriaramByIdmemoriaramadicional;
    }
    
    public void setMemoriaramByIdmemoriaramadicional(Memoriaram memoriaramByIdmemoriaramadicional) {
        this.memoriaramByIdmemoriaramadicional = memoriaramByIdmemoriaramadicional;
    }
    public Memoriaram getMemoriaramByIdmemoriaram() {
        return this.memoriaramByIdmemoriaram;
    }
    
    public void setMemoriaramByIdmemoriaram(Memoriaram memoriaramByIdmemoriaram) {
        this.memoriaramByIdmemoriaram = memoriaramByIdmemoriaram;
    }
    public Procesador getProcesador() {
        return this.procesador;
    }
    
    public void setProcesador(Procesador procesador) {
        this.procesador = procesador;
    }
    public Tarjetamadre getTarjetamadre() {
        return this.tarjetamadre;
    }
    
    public void setTarjetamadre(Tarjetamadre tarjetamadre) {
        this.tarjetamadre = tarjetamadre;
    }
    public Tarjetavideo getTarjetavideo() {
        return this.tarjetavideo;
    }
    
    public void setTarjetavideo(Tarjetavideo tarjetavideo) {
        this.tarjetavideo = tarjetavideo;
    }
    public BigDecimal getCostototal() {
        return this.costototal;
    }
    
    public void setCostototal(BigDecimal costototal) {
        this.costototal = costototal;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


