package com.pcsell.entity;
// Generated 14/01/2020 01:47:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MarcaProcesador generated by hbm2java
 */
public class MarcaProcesador  implements java.io.Serializable {


     private long id;
     private Imagen imagen;
     private String nombre;
     private Set procesadorDisipadors = new HashSet(0);
     private Set tarjetaMadres = new HashSet(0);
     private Set procesadors = new HashSet(0);

    public MarcaProcesador() {
    }

	
    public MarcaProcesador(long id, Imagen imagen, String nombre) {
        this.id = id;
        this.imagen = imagen;
        this.nombre = nombre;
    }
    public MarcaProcesador(long id, Imagen imagen, String nombre, Set procesadorDisipadors, Set tarjetaMadres, Set procesadors) {
       this.id = id;
       this.imagen = imagen;
       this.nombre = nombre;
       this.procesadorDisipadors = procesadorDisipadors;
       this.tarjetaMadres = tarjetaMadres;
       this.procesadors = procesadors;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Imagen getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Imagen imagen) {
        this.imagen = imagen;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProcesadorDisipadors() {
        return this.procesadorDisipadors;
    }
    
    public void setProcesadorDisipadors(Set procesadorDisipadors) {
        this.procesadorDisipadors = procesadorDisipadors;
    }
    public Set getTarjetaMadres() {
        return this.tarjetaMadres;
    }
    
    public void setTarjetaMadres(Set tarjetaMadres) {
        this.tarjetaMadres = tarjetaMadres;
    }
    public Set getProcesadors() {
        return this.procesadors;
    }
    
    public void setProcesadors(Set procesadors) {
        this.procesadors = procesadors;
    }




}


