package com.pcsell.entity;
// Generated 16/01/2020 08:44:30 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * MemoriaRam generated by hbm2java
 */
public class MemoriaRam  implements java.io.Serializable {


     private long id;
     private Imagen imagen;
     private String marca;
     private String modelo;
     private BigDecimal velocidad;
     private int capacidad;
     private BigDecimal precio;
     private String tipo;
     private Integer cantidad;
     private String descripcion;
     private Set computadorasForMemoriaRamAdicional = new HashSet(0);
     private Set computadorasForMemoriaRam = new HashSet(0);

    public MemoriaRam() {
    }

	
    public MemoriaRam(long id, Imagen imagen, String marca, String modelo, BigDecimal velocidad, int capacidad, BigDecimal precio) {
        this.id = id;
        this.imagen = imagen;
        this.marca = marca;
        this.modelo = modelo;
        this.velocidad = velocidad;
        this.capacidad = capacidad;
        this.precio = precio;
    }
    public MemoriaRam(long id, Imagen imagen, String marca, String modelo, BigDecimal velocidad, int capacidad, BigDecimal precio, String tipo, Integer cantidad, String descripcion, Set computadorasForMemoriaRamAdicional, Set computadorasForMemoriaRam) {
       this.id = id;
       this.imagen = imagen;
       this.marca = marca;
       this.modelo = modelo;
       this.velocidad = velocidad;
       this.capacidad = capacidad;
       this.precio = precio;
       this.tipo = tipo;
       this.cantidad = cantidad;
       this.descripcion = descripcion;
       this.computadorasForMemoriaRamAdicional = computadorasForMemoriaRamAdicional;
       this.computadorasForMemoriaRam = computadorasForMemoriaRam;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Imagen getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Imagen imagen) {
        this.imagen = imagen;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public BigDecimal getVelocidad() {
        return this.velocidad;
    }
    
    public void setVelocidad(BigDecimal velocidad) {
        this.velocidad = velocidad;
    }
    public int getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getComputadorasForMemoriaRamAdicional() {
        return this.computadorasForMemoriaRamAdicional;
    }
    
    public void setComputadorasForMemoriaRamAdicional(Set computadorasForMemoriaRamAdicional) {
        this.computadorasForMemoriaRamAdicional = computadorasForMemoriaRamAdicional;
    }
    public Set getComputadorasForMemoriaRam() {
        return this.computadorasForMemoriaRam;
    }
    
    public void setComputadorasForMemoriaRam(Set computadorasForMemoriaRam) {
        this.computadorasForMemoriaRam = computadorasForMemoriaRam;
    }




}


