package com.pcsell.entity;
// Generated 16/01/2020 11:03:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Procesador generated by hbm2java
 */
public class Procesador  implements java.io.Serializable {


     private long id;
     private Imagen imagen;
     private Marcaprocesador marcaprocesador;
     private String modelo;
     private int nucleos;
     private Integer hilosdeprocesamiento;
     private BigDecimal frecuenciabase;
     private BigDecimal tdp;
     private BigDecimal precio;
     private Integer cantidades;
     private String descripcion;
     private Set computadoras = new HashSet(0);

    public Procesador() {
    }

	
    public Procesador(long id, Imagen imagen, Marcaprocesador marcaprocesador, String modelo, int nucleos, BigDecimal precio) {
        this.id = id;
        this.imagen = imagen;
        this.marcaprocesador = marcaprocesador;
        this.modelo = modelo;
        this.nucleos = nucleos;
        this.precio = precio;
    }
    public Procesador(long id, Imagen imagen, Marcaprocesador marcaprocesador, String modelo, int nucleos, Integer hilosdeprocesamiento, BigDecimal frecuenciabase, BigDecimal tdp, BigDecimal precio, Integer cantidades, String descripcion, Set computadoras) {
       this.id = id;
       this.imagen = imagen;
       this.marcaprocesador = marcaprocesador;
       this.modelo = modelo;
       this.nucleos = nucleos;
       this.hilosdeprocesamiento = hilosdeprocesamiento;
       this.frecuenciabase = frecuenciabase;
       this.tdp = tdp;
       this.precio = precio;
       this.cantidades = cantidades;
       this.descripcion = descripcion;
       this.computadoras = computadoras;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Imagen getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Imagen imagen) {
        this.imagen = imagen;
    }
    public Marcaprocesador getMarcaprocesador() {
        return this.marcaprocesador;
    }
    
    public void setMarcaprocesador(Marcaprocesador marcaprocesador) {
        this.marcaprocesador = marcaprocesador;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public int getNucleos() {
        return this.nucleos;
    }
    
    public void setNucleos(int nucleos) {
        this.nucleos = nucleos;
    }
    public Integer getHilosdeprocesamiento() {
        return this.hilosdeprocesamiento;
    }
    
    public void setHilosdeprocesamiento(Integer hilosdeprocesamiento) {
        this.hilosdeprocesamiento = hilosdeprocesamiento;
    }
    public BigDecimal getFrecuenciabase() {
        return this.frecuenciabase;
    }
    
    public void setFrecuenciabase(BigDecimal frecuenciabase) {
        this.frecuenciabase = frecuenciabase;
    }
    public BigDecimal getTdp() {
        return this.tdp;
    }
    
    public void setTdp(BigDecimal tdp) {
        this.tdp = tdp;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Integer getCantidades() {
        return this.cantidades;
    }
    
    public void setCantidades(Integer cantidades) {
        this.cantidades = cantidades;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getComputadoras() {
        return this.computadoras;
    }
    
    public void setComputadoras(Set computadoras) {
        this.computadoras = computadoras;
    }




}


