package com.pcsell.entity;
// Generated 14/01/2020 01:47:30 PM by Hibernate Tools 4.3.1



/**
 * ProcesadorDisipadorId generated by hbm2java
 */
public class ProcesadorDisipadorId  implements java.io.Serializable {


     private long procesador;
     private long disipador;

    public ProcesadorDisipadorId() {
    }

    public ProcesadorDisipadorId(long procesador, long disipador) {
       this.procesador = procesador;
       this.disipador = disipador;
    }
   
    public long getProcesador() {
        return this.procesador;
    }
    
    public void setProcesador(long procesador) {
        this.procesador = procesador;
    }
    public long getDisipador() {
        return this.disipador;
    }
    
    public void setDisipador(long disipador) {
        this.disipador = disipador;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProcesadorDisipadorId) ) return false;
		 ProcesadorDisipadorId castOther = ( ProcesadorDisipadorId ) other; 
         
		 return (this.getProcesador()==castOther.getProcesador())
 && (this.getDisipador()==castOther.getDisipador());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getProcesador();
         result = 37 * result + (int) this.getDisipador();
         return result;
   }   


}


