package com.pcsell.entity;
// Generated 14/01/2020 01:47:30 PM by Hibernate Tools 4.3.1



/**
 * ProcesadorDisipador generated by hbm2java
 */
public class ProcesadorDisipador  implements java.io.Serializable {


     private ProcesadorDisipadorId id;
     private DisipadorCalor disipadorCalor;
     private MarcaProcesador marcaProcesador;

    public ProcesadorDisipador() {
    }

    public ProcesadorDisipador(ProcesadorDisipadorId id, DisipadorCalor disipadorCalor, MarcaProcesador marcaProcesador) {
       this.id = id;
       this.disipadorCalor = disipadorCalor;
       this.marcaProcesador = marcaProcesador;
    }
   
    public ProcesadorDisipadorId getId() {
        return this.id;
    }
    
    public void setId(ProcesadorDisipadorId id) {
        this.id = id;
    }
    public DisipadorCalor getDisipadorCalor() {
        return this.disipadorCalor;
    }
    
    public void setDisipadorCalor(DisipadorCalor disipadorCalor) {
        this.disipadorCalor = disipadorCalor;
    }
    public MarcaProcesador getMarcaProcesador() {
        return this.marcaProcesador;
    }
    
    public void setMarcaProcesador(MarcaProcesador marcaProcesador) {
        this.marcaProcesador = marcaProcesador;
    }




}


