package com.pcsell.entity;
// Generated 17/01/2020 02:39:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tamaniotm generated by hbm2java
 */
public class Tamaniotm  implements java.io.Serializable {


     private long id;
     private String tamanio;
     private Set tarjetamadres = new HashSet(0);
     private Set fuentepoders = new HashSet(0);
     private Set gabinetes = new HashSet(0);

    public Tamaniotm() {
    }

	
    public Tamaniotm(long id, String tamanio) {
        this.id = id;
        this.tamanio = tamanio;
    }
    public Tamaniotm(long id, String tamanio, Set tarjetamadres, Set fuentepoders, Set gabinetes) {
       this.id = id;
       this.tamanio = tamanio;
       this.tarjetamadres = tarjetamadres;
       this.fuentepoders = fuentepoders;
       this.gabinetes = gabinetes;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getTamanio() {
        return this.tamanio;
    }
    
    public void setTamanio(String tamanio) {
        this.tamanio = tamanio;
    }
    public Set getTarjetamadres() {
        return this.tarjetamadres;
    }
    
    public void setTarjetamadres(Set tarjetamadres) {
        this.tarjetamadres = tarjetamadres;
    }
    public Set getFuentepoders() {
        return this.fuentepoders;
    }
    
    public void setFuentepoders(Set fuentepoders) {
        this.fuentepoders = fuentepoders;
    }
    public Set getGabinetes() {
        return this.gabinetes;
    }
    
    public void setGabinetes(Set gabinetes) {
        this.gabinetes = gabinetes;
    }




}


