package com.pcsell.entity;
// Generated 16/01/2020 08:44:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TamanioTm generated by hbm2java
 */
public class TamanioTm  implements java.io.Serializable {


     private long id;
     private String tamanio;
     private Set tarjetaMadres = new HashSet(0);
     private Set fuentePoders = new HashSet(0);
     private Set gabinetes = new HashSet(0);

    public TamanioTm() {
    }

	
    public TamanioTm(long id, String tamanio) {
        this.id = id;
        this.tamanio = tamanio;
    }
    public TamanioTm(long id, String tamanio, Set tarjetaMadres, Set fuentePoders, Set gabinetes) {
       this.id = id;
       this.tamanio = tamanio;
       this.tarjetaMadres = tarjetaMadres;
       this.fuentePoders = fuentePoders;
       this.gabinetes = gabinetes;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getTamanio() {
        return this.tamanio;
    }
    
    public void setTamanio(String tamanio) {
        this.tamanio = tamanio;
    }
    public Set getTarjetaMadres() {
        return this.tarjetaMadres;
    }
    
    public void setTarjetaMadres(Set tarjetaMadres) {
        this.tarjetaMadres = tarjetaMadres;
    }
    public Set getFuentePoders() {
        return this.fuentePoders;
    }
    
    public void setFuentePoders(Set fuentePoders) {
        this.fuentePoders = fuentePoders;
    }
    public Set getGabinetes() {
        return this.gabinetes;
    }
    
    public void setGabinetes(Set gabinetes) {
        this.gabinetes = gabinetes;
    }




}


