package com.pcsell.entity;
// Generated 16/01/2020 11:03:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tarjetavideo generated by hbm2java
 */
public class Tarjetavideo  implements java.io.Serializable {


     private long id;
     private Imagen imagen;
     private String marca;
     private String modelo;
     private String vram;
     private int ram;
     private String conexion;
     private String descripcion;
     private BigDecimal precio;
     private Integer cantidad;
     private Set computadoras = new HashSet(0);

    public Tarjetavideo() {
    }

	
    public Tarjetavideo(long id, Imagen imagen, String marca, String modelo, String vram, int ram, BigDecimal precio) {
        this.id = id;
        this.imagen = imagen;
        this.marca = marca;
        this.modelo = modelo;
        this.vram = vram;
        this.ram = ram;
        this.precio = precio;
    }
    public Tarjetavideo(long id, Imagen imagen, String marca, String modelo, String vram, int ram, String conexion, String descripcion, BigDecimal precio, Integer cantidad, Set computadoras) {
       this.id = id;
       this.imagen = imagen;
       this.marca = marca;
       this.modelo = modelo;
       this.vram = vram;
       this.ram = ram;
       this.conexion = conexion;
       this.descripcion = descripcion;
       this.precio = precio;
       this.cantidad = cantidad;
       this.computadoras = computadoras;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Imagen getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Imagen imagen) {
        this.imagen = imagen;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getVram() {
        return this.vram;
    }
    
    public void setVram(String vram) {
        this.vram = vram;
    }
    public int getRam() {
        return this.ram;
    }
    
    public void setRam(int ram) {
        this.ram = ram;
    }
    public String getConexion() {
        return this.conexion;
    }
    
    public void setConexion(String conexion) {
        this.conexion = conexion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Set getComputadoras() {
        return this.computadoras;
    }
    
    public void setComputadoras(Set computadoras) {
        this.computadoras = computadoras;
    }




}


