package com.pcsell.entity;
// Generated 16/01/2020 08:44:30 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TarjetaMadre generated by hbm2java
 */
public class TarjetaMadre  implements java.io.Serializable {


     private long id;
     private Imagen imagen;
     private MarcaProcesador marcaProcesador;
     private TamanioTm tamanioTm;
     private String marca;
     private String modelo;
     private String ram;
     private String almacenamiento;
     private BigDecimal precio;
     private Integer cantidad;
     private String descripcion;
     private Set computadoras = new HashSet(0);

    public TarjetaMadre() {
    }

	
    public TarjetaMadre(long id, Imagen imagen, MarcaProcesador marcaProcesador, TamanioTm tamanioTm, String marca, String modelo, String ram, String almacenamiento, BigDecimal precio) {
        this.id = id;
        this.imagen = imagen;
        this.marcaProcesador = marcaProcesador;
        this.tamanioTm = tamanioTm;
        this.marca = marca;
        this.modelo = modelo;
        this.ram = ram;
        this.almacenamiento = almacenamiento;
        this.precio = precio;
    }
    public TarjetaMadre(long id, Imagen imagen, MarcaProcesador marcaProcesador, TamanioTm tamanioTm, String marca, String modelo, String ram, String almacenamiento, BigDecimal precio, Integer cantidad, String descripcion, Set computadoras) {
       this.id = id;
       this.imagen = imagen;
       this.marcaProcesador = marcaProcesador;
       this.tamanioTm = tamanioTm;
       this.marca = marca;
       this.modelo = modelo;
       this.ram = ram;
       this.almacenamiento = almacenamiento;
       this.precio = precio;
       this.cantidad = cantidad;
       this.descripcion = descripcion;
       this.computadoras = computadoras;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Imagen getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Imagen imagen) {
        this.imagen = imagen;
    }
    public MarcaProcesador getMarcaProcesador() {
        return this.marcaProcesador;
    }
    
    public void setMarcaProcesador(MarcaProcesador marcaProcesador) {
        this.marcaProcesador = marcaProcesador;
    }
    public TamanioTm getTamanioTm() {
        return this.tamanioTm;
    }
    
    public void setTamanioTm(TamanioTm tamanioTm) {
        this.tamanioTm = tamanioTm;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getRam() {
        return this.ram;
    }
    
    public void setRam(String ram) {
        this.ram = ram;
    }
    public String getAlmacenamiento() {
        return this.almacenamiento;
    }
    
    public void setAlmacenamiento(String almacenamiento) {
        this.almacenamiento = almacenamiento;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getComputadoras() {
        return this.computadoras;
    }
    
    public void setComputadoras(Set computadoras) {
        this.computadoras = computadoras;
    }




}


