package com.pcsell.entity;
// Generated 16/01/2020 11:03:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tarjetamadre generated by hbm2java
 */
public class Tarjetamadre  implements java.io.Serializable {


     private long id;
     private Imagen imagen;
     private Marcaprocesador marcaprocesador;
     private Tamaniotm tamaniotm;
     private String marca;
     private String modelo;
     private String ram;
     private String almacenamiento;
     private BigDecimal precio;
     private Integer cantidad;
     private String descripcion;
     private Set computadoras = new HashSet(0);

    public Tarjetamadre() {
    }

	
    public Tarjetamadre(long id, Imagen imagen, Marcaprocesador marcaprocesador, Tamaniotm tamaniotm, String marca, String modelo, String ram, String almacenamiento, BigDecimal precio) {
        this.id = id;
        this.imagen = imagen;
        this.marcaprocesador = marcaprocesador;
        this.tamaniotm = tamaniotm;
        this.marca = marca;
        this.modelo = modelo;
        this.ram = ram;
        this.almacenamiento = almacenamiento;
        this.precio = precio;
    }
    public Tarjetamadre(long id, Imagen imagen, Marcaprocesador marcaprocesador, Tamaniotm tamaniotm, String marca, String modelo, String ram, String almacenamiento, BigDecimal precio, Integer cantidad, String descripcion, Set computadoras) {
       this.id = id;
       this.imagen = imagen;
       this.marcaprocesador = marcaprocesador;
       this.tamaniotm = tamaniotm;
       this.marca = marca;
       this.modelo = modelo;
       this.ram = ram;
       this.almacenamiento = almacenamiento;
       this.precio = precio;
       this.cantidad = cantidad;
       this.descripcion = descripcion;
       this.computadoras = computadoras;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Imagen getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Imagen imagen) {
        this.imagen = imagen;
    }
    public Marcaprocesador getMarcaprocesador() {
        return this.marcaprocesador;
    }
    
    public void setMarcaprocesador(Marcaprocesador marcaprocesador) {
        this.marcaprocesador = marcaprocesador;
    }
    public Tamaniotm getTamaniotm() {
        return this.tamaniotm;
    }
    
    public void setTamaniotm(Tamaniotm tamaniotm) {
        this.tamaniotm = tamaniotm;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getRam() {
        return this.ram;
    }
    
    public void setRam(String ram) {
        this.ram = ram;
    }
    public String getAlmacenamiento() {
        return this.almacenamiento;
    }
    
    public void setAlmacenamiento(String almacenamiento) {
        this.almacenamiento = almacenamiento;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getComputadoras() {
        return this.computadoras;
    }
    
    public void setComputadoras(Set computadoras) {
        this.computadoras = computadoras;
    }




}


