package com.pcsell.entity;
// Generated 14/01/2020 01:47:30 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private long id;
    private String nombre;
    private String apellidos;
    private String coreoElectronico;
    private String contrasenia;
    private Set ventas = new HashSet(0);

    public Usuario() {
    }

    public Usuario(long id, String coreoElectronico, String contrasenia) {
        this.id = id;
        this.coreoElectronico = coreoElectronico;
        this.contrasenia = contrasenia;
    }

    public Usuario(long id, String nombre, String apellidos, String coreoElectronico, String contrasenia, Set ventas) {
        this.id = id;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.coreoElectronico = coreoElectronico;
        this.contrasenia = contrasenia;
        this.ventas = ventas;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public String getCoreoElectronico() {
        return this.coreoElectronico;
    }

    public void setCoreoElectronico(String coreoElectronico) {
        this.coreoElectronico = coreoElectronico;
    }

    public String getContrasenia() {
        return this.contrasenia;
    }

    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    public Set getVentas() {
        return this.ventas;
    }

    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }

}
