package com.pcsell.entity;
// Generated 17/01/2020 02:39:01 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private long id;
    private String nombre;
    private String apellidos;
    private String coreoElectronico;
    private String contrasenia;
    private Set ventas = new HashSet(0);

     private long id;
     private String nombre;
     private String apellidos;
     private String correoelectronico;
     private String contrasenia;
     private Set ventas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(long id, String correoelectronico, String contrasenia) {
        this.id = id;
        this.correoelectronico = correoelectronico;
        this.contrasenia = contrasenia;
    }
    public Usuario(long id, String nombre, String apellidos, String correoelectronico, String contrasenia, Set ventas) {
       this.id = id;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.correoelectronico = correoelectronico;
       this.contrasenia = contrasenia;
       this.ventas = ventas;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCorreoelectronico() {
        return this.correoelectronico;
    }
    
    public void setCorreoelectronico(String correoelectronico) {
        this.correoelectronico = correoelectronico;
    }

    public String getContrasenia() {
        return this.contrasenia;
    }

    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    public Set getVentas() {
        return this.ventas;
    }

    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }

}
