package com.pcsell.entity;
// Generated 17/01/2020 02:39:01 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private long id;
     private Computadora computadora;
     private Usuario usuario;
     private Date fechacompra;
     private int cantidad;
     private BigDecimal costo;
     private BigDecimal costoenvio;
     private BigDecimal costototal;
     private String lugarenvio;
     private String referencias;
     private String codigopostal;
     private String telefono;

    public Venta() {
    }

	
    public Venta(long id, Computadora computadora, Usuario usuario, Date fechacompra, int cantidad, BigDecimal costo, BigDecimal costototal, String lugarenvio, String codigopostal, String telefono) {
        this.id = id;
        this.computadora = computadora;
        this.usuario = usuario;
        this.fechacompra = fechacompra;
        this.cantidad = cantidad;
        this.costo = costo;
        this.costototal = costototal;
        this.lugarenvio = lugarenvio;
        this.codigopostal = codigopostal;
        this.telefono = telefono;
    }
    public Venta(long id, Computadora computadora, Usuario usuario, Date fechacompra, int cantidad, BigDecimal costo, BigDecimal costoenvio, BigDecimal costototal, String lugarenvio, String referencias, String codigopostal, String telefono) {
       this.id = id;
       this.computadora = computadora;
       this.usuario = usuario;
       this.fechacompra = fechacompra;
       this.cantidad = cantidad;
       this.costo = costo;
       this.costoenvio = costoenvio;
       this.costototal = costototal;
       this.lugarenvio = lugarenvio;
       this.referencias = referencias;
       this.codigopostal = codigopostal;
       this.telefono = telefono;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Computadora getComputadora() {
        return this.computadora;
    }
    
    public void setComputadora(Computadora computadora) {
        this.computadora = computadora;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechacompra() {
        return this.fechacompra;
    }
    
    public void setFechacompra(Date fechacompra) {
        this.fechacompra = fechacompra;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }
    public BigDecimal getCostoenvio() {
        return this.costoenvio;
    }
    
    public void setCostoenvio(BigDecimal costoenvio) {
        this.costoenvio = costoenvio;
    }
    public BigDecimal getCostototal() {
        return this.costototal;
    }
    
    public void setCostototal(BigDecimal costototal) {
        this.costototal = costototal;
    }
    public String getLugarenvio() {
        return this.lugarenvio;
    }
    
    public void setLugarenvio(String lugarenvio) {
        this.lugarenvio = lugarenvio;
    }
    public String getReferencias() {
        return this.referencias;
    }
    
    public void setReferencias(String referencias) {
        this.referencias = referencias;
    }
    public String getCodigopostal() {
        return this.codigopostal;
    }
    
    public void setCodigopostal(String codigopostal) {
        this.codigopostal = codigopostal;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


